language: node_js
node_js:
  - "v10.15.2"

before_script:
  - yarn install
  - cd frontend && yarn install && cd ..

script:
  - yarn test
  - cd frontend && yarn lint && yarn test && cd ..

deploy:
  provider: heroku
  api_key:
    master: $heroku_api_key
    develop: $heroku_api_key
    heroku_config: $heroku_api_key
  app:
    master: tp-revolution-prod
    develop: tp-revolution-dev
    heroku_config: $heroku_api_key

