language: node_js
node_js:
  - "v10.15.2"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - cd frontend && yarn install && cd ..

script:
  - cd frontend && yarn lint && yarn test && yarn build && cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: frontend/build
  on:
    branch: master


