export const SELECT_MACHINE = 'SELECT_MACHINE'
export const UNSELECT_MACHINE = 'UNSELECT_MACHINE'

export const SELECT_CELDA = 'SELECT_CELDA'
export const EDIT_MACHINE = 'EDIT_MACHINE'

export const UPDATE_CELLS = 'UPDATE_CELLS'
export const CLEAR_CELL = 'CLEAR_CELL'
export const ADD_MACHINE_TO_CELL = 'ADD_MACHINE_TO_CELL'