export const SELECT_MACHINE = 'SELECT_MACHINE'
export const UNSELECT_MACHINE = 'UNSELECT_MACHINE'

export const SELECT_CELDA = 'SELECT_CELDA'
export const UNSELECT_CELL = 'UNSELECT_CELL'
export const EDIT_MACHINE = 'EDIT_MACHINE'

export const UPDATE_CELLS = 'UPDATE_CELLS'
export const CLEAR_CELL = 'CLEAR_CELL'
export const ADD_MACHINE_TO_CELL = 'ADD_MACHINE_TO_CELL'
export const SELECT_MACHINE_2 = 'SELECT_MACHINE_2'
export const ROTATE_MACHINE = 'ROTATE_MACHINE'
export const MOVE_MACHINE = 'MOVE_MACHINE'


// game action types
export const LOGIN_USER = 'LOGIN_USER'
export const LOAD_FACTORIES = 'LOAD_FACTORIES'
